### ISSUE TITLE
use all defined keys in a file

### ISSUE THREAD

**Issue by bodepd** [jenkinsci/yaml-axis-plugin#13]
Hi,

I would like to just be able to completely trust all keys defined in a yaml file to be able to build out matrices based only on what's contained in a code repo. In this use case, exclude would just be treated as a special key value (and all others become axes for the build matrix)

Is this a patch you would consider merging if I do the work?

thanks,

Dan

**Comment by sue445** [comment]
@bodepd It's great ! But this is impossible on the specifications of the Jenkins...

One axis is one of the `hudson.matrix.Axis` instance. One instance can not have more than one axis.

Jenkins doesn't have extension point of a multiple axis

See https://wiki.jenkins-ci.org/display/JENKINS/Extension+points#Extensionpoints-ExtensionPointsinMatrixProjectPlugin

**Comment by bodepd** [comment]
thanks so much for this information before I spent a lot of time trying to figure it out :) Do you know if this is possible in Jenkins 2.0?

**Comment by sue445** [comment]
@bodepd When using jenkins 2.0, we can use pipeline DSL (e.g. read yaml from dsl file)
